# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'science.fit'
tagline:          'Data is the Commodity'
description:      'Thoughts and ideas of a passionate data scientist.'
url:              https://jtutmaher.github.io
baseurl:          /

author:
  name:           'Jacob Tutmaher'
  url:            https://github.com/jtutmaher

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jtutmaher/jtutmaher.github.io
