# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'Helix'
tagline:          'Jacob Tutmaher'
description:      'A blog for data, statistics, and everything inbetween.'
url:              https://jtutmaher.github.io
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Jacob Tutmaher'
  url:            https://linkedin.com/jacobtutmaher

paginate:         5
paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  
# Comment
disqus:
  shortname: jtutmaher

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false
  syntax_highlighter:   coderay
  coderay_line_numbers: inline
  math_engine:       mathjax		# or use  mathjax 
  math_engine_opts:
    preview:         true
    preview_as_code: true
